### PR TITLE
Make output of 'dump' proper XML.

### LINKED ISSUE #2: Output of garmin_dump is not proper XML
It is missing the <?xml> tag as well as a proper root node.

Issue is from https://code.google.com/archive/p/garmintools/issues/9

### PR DESCRIPTION
**Pull request by jasonmm**
This pull request will close #2.

This pull request adds the XML declaration to the top of the dumped XML data. It also surrounds all the data with a `<garmin>` tag and the data from each dumped file with an `<item>` tag. Both new tags are necessary because the _dump_ command can be used to combine the contents of multiple .gmn files.

If there are better tag names than "garmin" or "item" I would be happy to change the names.

### CODE REVIEW

**Comment by phako** [comment]
I would probably use "activity" instead of "item" similar to TCX, otherwise looks fine, thanks :)

**Comment by jasonmm** [comment]
That makes sense. I have changed it to "activity".

**Comment by phako** [comment]
I have noticed one minor issue:
```
<?xml version="1.0"?>
<garmin>
/home/jens/Source/garmintools/2020/06/20200619T184156.gmn: open: No such file or directory
</garmin>
```

**Comment by jasonmm** [comment]
Should error messages be sent to STDERR instead of STDOUT? 

For example, https://github.com/phako/garmintools/blob/master/src/unpack.c#L1230 would become `fprintf(stderr, "%s: open: %s\n",filename,strerror(errno));`.

Would that be acceptable?

**Comment by phako** [comment]
yes, sounds reasonsable

**Pull request merged**
